import "../globals.css";
import Footer from "@/composants/Footer";

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="">
        {children}
        <Footer />
      </body>
    </html>
  );
}
