import "../globals.css";
import Sidebar from "@/composants/Sidebar";

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="">
        <div className="flex min-h-screen bg-gray-100">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
